In [1]:
import numpy as np
import pandas as pd
f = [x**2 for x in range(101, 1000,2)]
bigdata = np.array([f]) # это подготовка массива к заданиям 8-10 в юните 9.7
bigdata

array([[ 10201,  10609,  11025,  11449,  11881,  12321,  12769,  13225,
         13689,  14161,  14641,  15129,  15625,  16129,  16641,  17161,
         17689,  18225,  18769,  19321,  19881,  20449,  21025,  21609,
         22201,  22801,  23409,  24025,  24649,  25281,  25921,  26569,
         27225,  27889,  28561,  29241,  29929,  30625,  31329,  32041,
         32761,  33489,  34225,  34969,  35721,  36481,  37249,  38025,
         38809,  39601,  40401,  41209,  42025,  42849,  43681,  44521,
         45369,  46225,  47089,  47961,  48841,  49729,  50625,  51529,
         52441,  53361,  54289,  55225,  56169,  57121,  58081,  59049,
         60025,  61009,  62001,  63001,  64009,  65025,  66049,  67081,
         68121,  69169,  70225,  71289,  72361,  73441,  74529,  75625,
         76729,  77841,  78961,  80089,  81225,  82369,  83521,  84681,
         85849,  87025,  88209,  89401,  90601,  91809,  93025,  94249,
         95481,  96721,  97969,  99225, 100489, 101761, 103041, 

In [2]:
bigdata[0::,::2] # делаем срез по нечетным индексам

array([[ 10201,  11025,  11881,  12769,  13689,  14641,  15625,  16641,
         17689,  18769,  19881,  21025,  22201,  23409,  24649,  25921,
         27225,  28561,  29929,  31329,  32761,  34225,  35721,  37249,
         38809,  40401,  42025,  43681,  45369,  47089,  48841,  50625,
         52441,  54289,  56169,  58081,  60025,  62001,  64009,  66049,
         68121,  70225,  72361,  74529,  76729,  78961,  81225,  83521,
         85849,  88209,  90601,  93025,  95481,  97969, 100489, 103041,
        105625, 108241, 110889, 113569, 116281, 119025, 121801, 124609,
        127449, 130321, 133225, 136161, 139129, 142129, 145161, 148225,
        151321, 154449, 157609, 160801, 164025, 167281, 170569, 173889,
        177241, 180625, 184041, 187489, 190969, 194481, 198025, 201601,
        205209, 208849, 212521, 216225, 219961, 223729, 227529, 231361,
        235225, 239121, 243049, 247009, 251001, 255025, 259081, 263169,
        267289, 271441, 275625, 279841, 284089, 288369, 292681, 

In [4]:
bigdata[::2] # а вот срез по четным индексам не получается

array([[ 10201,  10609,  11025,  11449,  11881,  12321,  12769,  13225,
         13689,  14161,  14641,  15129,  15625,  16129,  16641,  17161,
         17689,  18225,  18769,  19321,  19881,  20449,  21025,  21609,
         22201,  22801,  23409,  24025,  24649,  25281,  25921,  26569,
         27225,  27889,  28561,  29241,  29929,  30625,  31329,  32041,
         32761,  33489,  34225,  34969,  35721,  36481,  37249,  38025,
         38809,  39601,  40401,  41209,  42025,  42849,  43681,  44521,
         45369,  46225,  47089,  47961,  48841,  49729,  50625,  51529,
         52441,  53361,  54289,  55225,  56169,  57121,  58081,  59049,
         60025,  61009,  62001,  63001,  64009,  65025,  66049,  67081,
         68121,  69169,  70225,  71289,  72361,  73441,  74529,  75625,
         76729,  77841,  78961,  80089,  81225,  82369,  83521,  84681,
         85849,  87025,  88209,  89401,  90601,  91809,  93025,  94249,
         95481,  96721,  97969,  99225, 100489, 101761, 103041, 